version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: luckysix
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  api:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/luckysix
      REDIS_URL: redis://redis:6379
      PORT: 8080
      CORS_ORIGIN: http://localhost:5173
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      - redis
    command: sh -c "npx prisma migrate deploy && node dist/index.js"

volumes:
  pgdata: {}
